version: '3.8'

services:
  pamtek-hr-helper:
    image: pamtek-hr-helper:latest
    container_name: pamtek-hr-helper
    ports:
      - "5000:5000"
    environment:
      - PAMTEK_USER_ID=${PAMTEK_USER_ID}
      - PAMTEK_PASSWORD=${PAMTEK_PASSWORD}
    restart: unless-stopped
    shm_size: '2gb'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
